@startuml
start

:Načítání hry;
:Inicializace systému;
:Načtení mapy;

:Zobrazení úvodního dialogu;

while (hráč nedosáhl poslední místnosti?) is (ano)
  :Získání seznamu dostupných místností;
  :Zkontrolovat reputaci hráče;
  if (místnost dostupná podle reputace?) then (ano)
    :Zobrazit dostupné místnosti;
    :Hráč si vybere místnost;
    :Vstup do místnosti;
  else (ne)
    :Zobrazit chybovou zprávu;
  endif

  while (hráč v místnosti) is (ano)
    :Uživatel zadá příkaz;
    switch (příkaz)
      case ("pohyb")
        :Zkontrolovat, zda lze jít do místnosti;
        if (možno vstoupit) then (ano)
          :Přesun do nové místnosti;
          break
        else (ne)
          :Zobrazit chybovou zprávu;
        endif
      case ("sebrat předmět")
        :Zkontrolovat, zda je předmět v místnosti;
        if (předmět existuje) then (ano)
          :Přidat předmět do inventáře;
        else (ne)
          :Zobrazit chybovou zprávu;
        endif
      case ("konverzace")
        :Zahájit rozhovor s NPC;
        while (interakce aktivní) is (ano)
          :Uživatel zadá příkaz;
          switch (příkaz)
            case ("boj")
              while (protivník není poražen?) is (ano)
                :Spustit bojový režim;
                :Zkontrolovat, zda byl protivník poražen;
              endwhile
            case ("řešit hádanku")
              while (řešení není správné?) is (ano)
                :Ověřit správnost řešení;
                if (správné?) then (ano)
                  :Odměna hráči;
                else (ne)
                  :Zobrazit nápovědu nebo chybovou zprávu;
                endif
              endwhile
            case ("dát předmět")
              :Předmět předán NPC;
          endswitch
        endwhile
      case ("otevřít inventář")
        :Zobrazit obsah inventáře;
      case (default)
        :Zobrazit chybovou zprávu;
    endswitch
  endwhile
endwhile

:Gratulace! Hráč vyhrál hru;
stop
@enduml
